#!/usr/bin/env bash
# A bash script that transfers a file from clients to a server

if [ "$#" -lt 4 ];
then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY_PATH="$4"

scp -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" "$FILE_PATH" "$USERNAME@$SERVER_IP":~/ || exit 1

echo "File transferred successfully to $USERNAME@$SERVER_IP:~/"
