#!/bin/bash
# Update package list and install nginx

apt-get update
apt-get install -y nginx

sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

service nginx restart > /dev/null 2>&1

echo "<html><body>Hello World!</body></html>" > /var/www/html/index.html

echo "Nginx installed and configured successfully."